### PR TITLE
Updating duration options on data elements

### PR DESCRIPTION
**Pull request by thebenrob**
Adding the "None" option to the data element duration.  Also cleaning up the descriptive text on the other options to be a little more consistent/descriptive.

### CODE REVIEW

**Comment by thebenrob** [comment]
@srhoades-adobe, will you please review?

**Review by srhoades-adobe — APPROVED** [review]

**Comment by Aaronius** [comment]
I noticed it's saying that the data element values are stored in cookies. That's no longer the case. See https://medium.com/launch-by-adobe/data-persistence-from-dtm-to-launch-52d26b834b54

Do one of you want to update the docs accordingly? If not, I can.

**Comment by thebenrob** [comment]
@Aaronius, I'll do the cookies thing in a separate PR.

**Comment by srhoades-adobe** [comment]
I’ll change the page to match the article you referenced.

**Pull request merged**
